#include "include/core/SkCanvas.h"
#include "include/core/SkFont.h"
#include "include/core/SkPaint.h"
#include <list>
#include <chrono>
#include <string>
#include "Block.h"
#include "Timeline.h"

//ALL GENERATED BY GRAFFEL IN A SUBCLASS OF Block

void graffel::Block::drawMe()
    {
    drawBlock();
    }
